from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


BASE_DIR = Path(__file__).parent
SNAPSHOT_DIR = BASE_DIR / "session_cache"


@st.cache_data(show_spinner=False)
def load_snapshot(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_snapshot_from_upload(uploaded_file) -> dict[str, Any]:
    return json.loads(uploaded_file.getvalue().decode("utf-8"))


def find_snapshot_files() -> list[Path]:
    files = sorted(SNAPSHOT_DIR.glob("session-*.json"), reverse=True)
    return files


def holdings_dataframe(snapshot: dict[str, Any]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for account in snapshot.get("accounts", []):
        account_id = account.get("account_id")
        account_type = account.get("account_type")
        for inv in account.get("investments", []):
            rows.append(
                {
                    "account_id": account_id,
                    "account_type": account_type,
                    "ticker": inv.get("stock_ticker"),
                    "security_name": inv.get("security_name"),
                    "sedol_code": inv.get("sedol_code"),
                    "units_held": inv.get("units_held", 0.0),
                    "price_pence": inv.get("price_pence", 0.0),
                    "value_gbp": inv.get("value_gbp", 0.0),
                    "cost_gbp": inv.get("cost_gbp", 0.0),
                    "gain_loss_gbp": inv.get("gain_loss_gbp", 0.0),
                    "gain_loss_percentage": inv.get("gain_loss_percentage", 0.0),
                    "purchase_time": inv.get("purchase_time"),
                    "purchase_time_note": inv.get("purchase_time_note"),
                }
            )

    return pd.DataFrame(rows)


def account_summary_dataframe(snapshot: dict[str, Any]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for account in snapshot.get("accounts", []):
        rows.append(
            {
                "account_id": account.get("account_id"),
                "account_type": account.get("account_type"),
                "stock_value_gbp": account.get("stock_value_gbp", 0.0),
                "total_cash_gbp": account.get("total_cash_gbp", 0.0),
                "amount_available_to_invest_gbp": account.get("amount_available_to_invest_gbp", 0.0),
                "total_value_gbp": account.get("total_value_gbp", 0.0),
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    st.set_page_config(page_title="HL Holdings Dashboard", layout="wide")
    st.title("HL Holdings Dashboard")
    st.caption("Data source: snapshot JSON files generated by your HL script")

    uploaded_snapshot = st.sidebar.file_uploader(
        "Upload snapshot JSON",
        type=["json"],
        help="Use this when running on Streamlit Cloud and local session_cache files are not present."
    )

    snapshots = find_snapshot_files() if SNAPSHOT_DIR.exists() else []

    snapshot = None
    selected_file = None

    if uploaded_snapshot is not None:
        snapshot = load_snapshot_from_upload(uploaded_snapshot)
        st.sidebar.success("Using uploaded snapshot")
    elif snapshots:
        snapshot_labels = [p.name for p in snapshots]
        selected_label = st.sidebar.selectbox("Snapshot", snapshot_labels, index=0)
        selected_file = SNAPSHOT_DIR / selected_label
        snapshot = load_snapshot(selected_file)
        st.sidebar.write("Selected file:")
        st.sidebar.code(str(selected_file), language="text")
    else:
        st.error("No local snapshots found. Upload a session-*.json file in the sidebar.")
        st.info("Tip: Create snapshots locally with your holdings script, then upload one here.")
        return

    st.subheader("Snapshot")
    c1, c2, c3 = st.columns(3)
    c1.metric("Snapshot ID", snapshot.get("snapshot_id", "-"))
    c2.metric("Snapshot UTC", snapshot.get("snapshot_time_utc", "-"))
    c3.metric("Unique Holdings", snapshot.get("unique_holdings_count", 0))

    accounts_df = account_summary_dataframe(snapshot)
    holdings_df = holdings_dataframe(snapshot)

    st.subheader("Account Totals")
    if not accounts_df.empty:
        st.dataframe(
            accounts_df,
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("No account totals in this snapshot.")

    st.subheader("Portfolio Totals")
    if not holdings_df.empty:
        total_value = float(holdings_df["value_gbp"].sum())
        total_cost = float(holdings_df["cost_gbp"].sum())
        total_gain = float(holdings_df["gain_loss_gbp"].sum())
        gain_pct = (total_gain / total_cost * 100.0) if total_cost else 0.0

        p1, p2, p3, p4 = st.columns(4)
        p1.metric("Total Value", f"GBP {total_value:,.2f}")
        p2.metric("Total Cost", f"GBP {total_cost:,.2f}")
        p3.metric("Gain/Loss", f"GBP {total_gain:,.2f}")
        p4.metric("Gain/Loss %", f"{gain_pct:,.2f}%")

        account_options = ["All"] + sorted(holdings_df["account_type"].dropna().unique().tolist())
        selected_account = st.selectbox("Filter account", account_options)

        filtered = holdings_df if selected_account == "All" else holdings_df[holdings_df["account_type"] == selected_account]

        st.subheader("Holdings")
        st.dataframe(
            filtered.sort_values("value_gbp", ascending=False),
            use_container_width=True,
            hide_index=True,
        )

        st.subheader("Top Positions By Value")
        top_positions = (
            filtered[["security_name", "value_gbp"]]
            .groupby("security_name", as_index=False)
            .sum()
            .sort_values("value_gbp", ascending=False)
            .head(10)
            .set_index("security_name")
        )
        st.bar_chart(top_positions)

        st.subheader("Top Gainers / Losers")
        gainers = filtered.sort_values("gain_loss_gbp", ascending=False).head(5)
        losers = filtered.sort_values("gain_loss_gbp", ascending=True).head(5)

        g1, g2 = st.columns(2)
        with g1:
            st.write("Top 5 Gainers")
            st.dataframe(gainers[["security_name", "gain_loss_gbp", "gain_loss_percentage"]], use_container_width=True, hide_index=True)
        with g2:
            st.write("Top 5 Losers")
            st.dataframe(losers[["security_name", "gain_loss_gbp", "gain_loss_percentage"]], use_container_width=True, hide_index=True)
    else:
        st.info("No holdings in this snapshot.")

    st.subheader("Data Notes")
    notes = snapshot.get("notes", {})
    if notes:
        st.json(notes)


if __name__ == "__main__":
    main()
